name: Run Tests
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_dispatch:

env:
  NO_COLOR: true
  CI: 1

jobs:
  build:
    name: Test
    timeout-minutes: 5
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Run Tests
        run: bun run test
