name: Run Tests
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_dispatch:

env:
  NO_COLOR: true
  CI: 1

jobs:
  build:
    name: Test
    timeout-minutes: 15
#     runs-on: [self-hosted]
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup yarn
        run: |
          mkdir -p ~/.local/bin
          curl -fsSL \
            https://github.com/yarnpkg/yarn/releases/download/v1.22.18/yarn-1.22.18.js > ~/.local/bin/yarn
          chmod +x ~/.local/bin/yarn

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Dependencies
        run: echo "Installing dependencies" && yarn install && echo "Done installing dependencies"

      - name: Run Tests
        run: yarn test
