name: Update Database
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # hourly

env:
  NO_COLOR: true
  CI: 1

jobs:
  restore:
    name: Update Database
    timeout-minutes: 10
    runs-on: [ubuntu-20.04]
    if: endsWith(github.ref, '/main')
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: bun install

      - name: Update Database
        run: node scripts/getLatestFPLDatabase.mjs --clone

      - name: Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # push-branch: 'master'
          commit-message: '[skip ci] Update Database'
          force-add: 'true'
          files: src/assets/fpl.db
          name: Divyendu Singh (Bot)
          email: divyendu.z@gmail.com
          rebase: 'true'
